AppBundle\Entity\User:
    attributes:
        uuid:
            groups: ['allUsers', 'oneProduct', 'oneUser']
        username:
            groups: ['allUsers', 'oneProduct', 'oneUser']
        plainPassword:
            groups: ['oneUser']
        email:
            groups: ['allUsers', 'oneUser']
        isActive:
            groups: ['allUsers', 'oneUser']
        roles:
            groups: ['allUsers', 'oneUser']
        products:
            groups: ['oneUser']


AppBundle\Entity\Product:
    attributes:
        uuid:
            groups: ['oneUser', 'oneProduct', 'allProducts', 'oneCat', 'oneCity', 'oneTag']
        title:
            groups: ['oneUser', 'oneProduct', 'allProducts', 'oneCat', 'oneCity', 'oneTag']
        description:
            groups: ['oneProduct']
        image:
            groups: ['oneUser', 'oneProduct', 'allProducts', 'oneCat', 'oneCity', 'oneTag']
        ref:
            groups: ['oneUser', 'oneProduct', 'allProducts']
        createdAt:
            groups: ['oneUser', 'oneProduct', 'allProducts']
        autoDeleteAt:
            groups: ['oneUser','oneProduct']
        city:
            groups: ['oneProduct']
        tags:
            groups: ['oneProduct']
        category:
            groups: ['oneUser', 'oneProduct']
        user:
            groups: ['oneProduct']

AppBundle\Entity\Category:
    attributes:
        id:
            groups: ['allCat', 'oneCat', 'oneProduct']
        uuid:
            groups: ['allCat', 'oneCat', 'oneProduct']
        name:
            groups: ['allCat', 'oneCat', 'oneProduct']
        products:
            groups: ['oneCat']

AppBundle\Entity\City:
    attributes:
        id:
            groups: ['allCities']
        uuid:
            groups: ['allCities', 'oneCity', 'oneProduct']
        name:
            groups: ['allCities', 'oneCity', 'oneProduct', 'allProducts']
        address:
            groups: ['allCities', 'oneCity', 'oneProduct']
        contactMessage:
            groups: ['oneCity', 'oneProduct']
        products:
            groups: ['oneCity']

AppBundle\Entity\Tag:
    attributes:
        id:
            groups: ['allTags']
        uuid:
            groups: ['allTags', 'oneTag', 'oneProduct', 'allProducts']
        name:
            groups: ['allTags', 'oneTag', 'oneProduct', 'allProducts']
        products:
            groups: ['oneTag']
