AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - NotBlank: ~
            - Type: string
        plainPassword:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        isActive:
            - NotBlank: ~